### ISSUE TITLE
All pages: Modal right-side padding issue

### ISSUE THREAD

**Issue by visuale** [forge/website-design#11]
Modal opening. In some browsers, there is padding (15px to the right) being added to the <body> class. See if there is a way to prevent that.

**Comment by gastaldi** [comment]
Looks like this is a known bug in Bootstrap: https://github.com/twbs/bootstrap/issues/9855

**Comment by gastaldi** [comment]
Or this: https://github.com/twbs/bootstrap/issues/14040
