### ISSUE TITLE
Addons: Secondary Addon page required

### ISSUE THREAD

**Issue by visuale** [forge/website-design#32]
A secondary addon page will be needed (functions in phone breakpoints only) to compliment the modal popup for add ons in the larger screen versions. My assumption is that this was intended to be a fly-in feature but since that doesn't work it seems that a sub-page link would be the next logical option. A fly-over menu-type appearance could be added but that seems like it might make navigation back to main page a little confusing.

**Comment by lincolnthree** [comment]
Yeah, I think a secondary addon page is fine. No need to get too fancy here.

**Comment by lincolnthree** [comment]
It can use the same layout as the single document page. WDYT?

**Comment by gastaldi** [comment]
:+1:
