### ISSUE TITLE
Addons Page: Please review breakpoints for smallest screen width changes

### ISSUE THREAD

**Issue by visuale** [forge/website-design#36]
Could everyone have a look at this? Right now, the individual addon boxes are set to drop to 2 per row at the smallest breakpoints, but I think that leaves them looking awfully thin. Plus, I can't prevent the text from overlapping the div borders at that width. I'd like to set these to be one addon per row at the smallest breakpoint.

**Comment by gastaldi** [comment]
I think that changing to be 1 addon/row is a good idea at the smallest breakpoint :+1:

**Comment by gastaldi** [comment]
Addons page for reference: https://rawgit.com/forge/website-design/master/addons.html

**Comment by visuale** [comment]
Thanks for catching that. A fix should be easy.

**Comment by lincolnthree** [comment]
Looking now!

**Comment by lincolnthree** [comment]
Ok, I think that's probably a good idea (1 addon/row at smallest breakpoint). They are a bit too squished and the text starts to overlap as you said. (Not much we can do about that if there is too much text - aside from making the box bigger, but we can limit # of characters).

I agree, make it 1/row at smallest breakpoint!
