### ISSUE TITLE
Search input fields are not sized equally with search buttons

### ISSUE THREAD

**Issue by lincolnthree** [forge/website-design#38]
The search text input field is not the same size as the submit button, see screenshot:

![screen shot 2015-04-06 at 10 13 25 am](https://cloud.githubusercontent.com/assets/362329/7005442/002b7f2e-dc46-11e4-86fb-1e47bc77ba72.png)

**Comment by visuale** [comment]
Yes, saw this when testing the widths. There's a fix for it in the next batch of things I'm pushing up.

**Comment by visuale** [comment]
Do you see this happening now for you?

**Comment by gastaldi** [comment]
It seems fixed to me :+1:

**Comment by lincolnthree** [comment]
Hmm, still seems to be happening for me in Chrome.

**Comment by lincolnthree** [comment]
Nm. Fixed for me. It seems Rawgit hadn't updated yet. I pulled it down locally and it looks perfect
