### ISSUE TITLE
Community page: Height of 1st and 4th grey boxes is uneven until first horizontal resize

### ISSUE THREAD

**Issue by lincolnthree** [forge/website-design#42]
Before resize:

![screen shot 2015-04-16 at 5 09 15 pm](https://cloud.githubusercontent.com/assets/362329/7191420/54ec15c4-e45b-11e4-962f-5dde15402710.png)
After resize:

![screen shot 2015-04-16 at 5 09 22 pm](https://cloud.githubusercontent.com/assets/362329/7191422/581e3970-e45b-11e4-8c3c-d0690d885432.png)

**Comment by visuale** [comment]
I think I figured out why – there's a margin rule in here that is affecting the way this displays that I hadn't noticed was there.  Removing that and re-writing the JS a little.

**Comment by lincolnthree** [comment]
Beautiful! Looks good now.
