### ISSUE TITLE
News Page: Three corners (tr, bl, br) of each entry are still bleeding out of the rounded edge

### ISSUE THREAD

**Issue by lincolnthree** [forge/website-design#43]
![screen shot 2015-04-16 at 5 11 18 pm](https://cloud.githubusercontent.com/assets/362329/7191452/a62982e6-e45b-11e4-83c6-1930331383ae.png)

**Comment by visuale** [comment]
@gastaldi Do you see this happening, too? I can't get this to happen in my version (trying in multiple browsers). I tried to zoom the text way up, too, to see if that made any difference. Still looks normal to me.

**Comment by gastaldi** [comment]
This is what I see ![Imgur](http://i.imgur.com/zvCGFuv.png)

**Comment by visuale** [comment]
Can you give this one another shot? I made a minor change to CSS.

**Comment by lincolnthree** [comment]
Yes! Fixed!!!
