### ISSUE TITLE
Documentation single page: Social share icons not vertically aligned at same height as other elements 

### ISSUE THREAD

**Issue by lincolnthree** [forge/website-design#45]
Seems like these should be vertically aligned together:

![screen shot 2015-04-16 at 5 16 35 pm](https://cloud.githubusercontent.com/assets/362329/7191560/849964ce-e45c-11e4-8e3b-8b6cd1bbedb3.png)

**Comment by lincolnthree** [comment]
![screen shot 2015-04-16 at 5 18 11 pm](https://cloud.githubusercontent.com/assets/362329/7191565/93e02ca6-e45c-11e4-8d9f-9a3904ad4649.png)

**Comment by visuale** [comment]
I'm tweaking this a bit... I had interpreted this to be that the three elements were to be as closely vertically center-aligned as possible. I'll get "Authors" and the social icons vertically top-aligned then try and get "Share" as close to center as possible.
