### ISSUE TITLE
CSS3 Flexbox support

### ISSUE THREAD

**Issue by gastaldi** [forge/website-design#49]
Jim, I've been working on creating the grid-based layout from our data and I am having some issues with the layout. 

Take for example the Advanced Search options layout in the News and the Documentation pages, where we'll have 3 items per column. 

According to the HTML, it should create a set of nested DIV tags for each group of 3 items and break after every 6 items to a new column. I was wondering if we could use CSS3 Flexbox[1][2] instead and let the arrangement work to the CSS. What do you think about it? 

[1] https://css-tricks.com/snippets/css/a-guide-to-flexbox/
[2] http://www.sketchingwithcss.com/samplechapter/cheatsheet.html#column

**Comment by gastaldi** [comment]
I think that the following might work as expected:

In the news page, replace

``` html
<div class="col-sm-6 col-sm-offset-0 col-xs-5 col-xs-offset-2 checkbox-columns">
```

with

``` html
<div style="display: flex;flex-flow: column wrap;height:120px;width:170px">
```

and add lots of the following tags inside of it (for testing purposes)

``` html
    <div class=" checkbox-row">
          <input type="checkbox" class="search-checkbox" id="latest-versions"> 
          <label class="checkbox-label" for="latest-versions"><span></span>Latest Versions</label>
     </div>
```

The layout still needs to be adjusted to mobile views, but that's a start.
Thoughts?

**Comment by visuale** [comment]
Sorry for the delay George, I'm just seeing this now. I'll have an answer to you Friday afternoon for sure.

**Comment by visuale** [comment]
@gastaldi , this is sort of working. I'm still playing with it a little but you can see here with borders showing (I'm using a second set of checkboxes in the Documentation main page):
![screen shot 2015-05-15 at 9 40 10 pm](https://cloud.githubusercontent.com/assets/26826/7664403/15faec8a-fb4b-11e4-89a0-6bb9aa199919.png)

**Comment by gastaldi** [comment]
It's looking good. Way to go :)

**Comment by gastaldi** [comment]
Looking good. Just tested with the news page

**Comment by gastaldi** [comment]
@visuale, Can we use it in the addons page too?

**Comment by visuale** [comment]
@gastaldi  Definitely. Getting this ready now.

**Comment by gastaldi** [comment]
The intention is to use this for the addon boxes, not the search options only.

**Comment by visuale** [comment]
Okay, understood. I just applied this to Addons search boxes. I'll convert the addon boxes as well.

**Comment by visuale** [comment]
Little update here: I just noticed that the star rating row isn't jumping down on window resize. I'll have a look at that, too.

**Comment by gastaldi** [comment]
We'll also need that for the documentation boxes in the documentation.html page.

**Comment by gastaldi** [comment]
Any expected date for the documentation boxes change? This is much needed asap.

**Comment by visuale** [comment]
Please review these as I had to resort to some trial & error to get the items to space evenly (more error than trial). I also saw a little bug with Safari that I have to go back and apply changes to for the advanced search boxes.
