### ISSUE TITLE
Apply .flex update to add-on boxes for Safari view

### ISSUE THREAD

**Issue by visuale** [forge/website-design#51]

**Comment by visuale** [comment]
Changing this back to open. @gastaldi I'd like to flag your attention to this one as it involved some css changes to all three areas where the flex-based grids are in use. I also removed the previous Bootstrap-based checkbox grids on documentation.html

**Comment by gastaldi** [comment]
Hi @visuale,
I applied your changes, but it seems that the addon boxes are too close to each other. Here is a sample of what I mean: 

![Imgur](http://i.imgur.com/bV3d3Bh.png)

**Comment by visuale** [comment]
I see... that doesn't look hard to fix. I'll get on it asap.

**Comment by visuale** [comment]
I only see this happening in Firefox. I applied a -moz exception for that rule.

**Comment by gastaldi** [comment]
Perfect! Thank you very much
